# Настройки торговой стратегии
strategy:
  signal_threshold: 0.7
  min_spread: 0.02
  max_volatility: 0.05
  timeframes: ["1m", "5m", "15m"]
  use_stop_loss: true
  use_take_profit: true

risk:
  max_daily_loss_pct: 3.0
  risk_per_trade_pct: 1.0
  leverage: 5
